[theme]
primaryColor = "#FDF9F0"
backgroundColor = "#99775C"
secondaryBackgroundColor = "#EAE7DD"
textColor = "#212529"
codeBackgroundColor = "#EAE7DD"
dataframeHeaderBackgroundColor = "#EAE7DD"
font = "sans serif"
